# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimmy Q的博客
email: marioqsc2013@hotmail.com
description: 我是jimmy，我在这里记录我的学习
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jimmyqsc.github.io" # the base hostname & protocol for your site
github_username:  JimmyQsc
bg-img: /images/header-bg.jpg
paginate: 5
home_message: Every Thing is Awesome
highlighter: rouge

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: [README.md]

# Default settings
defaults:
  -
    scope:
      path: ""
      type: 'posts'
    values:
      is_post: true
      author: Jimmy Q
      layout: 'post'
      comments: true
      bg-img: http://i.niupic.com/images/2016/08/10/vHRiPJ.jpg

